version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/projects/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock/:/var/run/docker.sock
    restart: unless-stopped
    privileged: true
    network_mode: host
  ha-support-service:
    container_name: ha-support-service
    build: ../ha-support-service
    environment:
      - HOST_URL=/ha-support
    volumes:
      - /home/pi/projects/home-assistant/public_files:/mnt/public
    restart: unless-stopped
    network_mode: host
