version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/pi/projects/nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - /home/pi/projects/nginx/certbot/www/:/var/www/certbot/:ro
      - /home/pi/projects/nginx/certbot/conf/:/etc/nginx/ssl/:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  certbot:
    image: certbot/certbot:arm32v6-latest
    volumes:
      - /home/pi/projects/nginx/certbot/www/:/var/www/certbot/:rw
      - /home/pi/projects/nginx/certbot/conf/:/etc/letsencrypt/:rw


